version: 2
updates:
  # API dependencies
  - package-ecosystem: "npm"
    directory: "/api"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "hellovaibhav" "Saquib1973"
    assignees:
      - "hellovaibhav"
    commit-message:
      prefix: "chore(api)"
      include: "scope"
    labels:
      - "dependencies"
      - "api"
      
  # Client dependencies
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "hellovaibhav"
    assignees:
      - "hellovaibhav"
    commit-message:
      prefix: "chore(client)"
      include: "scope"
    labels:
      - "dependencies"
      - "client"
      
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "hellovaibhav"
    assignees:
      - "hellovaibhav"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
